import { Milestone } from '../types';
import { format } from 'date-fns';

export const generateICS = (milestones: Milestone[], appName: string = "Life Milestones"): string => {
  const lineBreak = '\r\n';
  
  let icsContent = [
    'BEGIN:VCALENDAR',
    'VERSION:2.0',
    `PRODID:-//${appName}//NONSGML v1.0//EN`,
    'CALSCALE:GREGORIAN',
    'METHOD:PUBLISH',
  ].join(lineBreak) + lineBreak;

  milestones.forEach((milestone) => {
    // ICS date format: YYYYMMDD
    const dateStr = format(milestone.date, 'yyyyMMdd');
    const uid = `${milestone.id}@lifemilestones.app`;
    
    const event = [
      'BEGIN:VEVENT',
      `UID:${uid}`,
      `DTSTAMP:${format(new Date(), "yyyyMMdd'T'HHmmss")}`,
      `DTSTART;VALUE=DATE:${dateStr}`,
      `SUMMARY:${milestone.title}`,
      `DESCRIPTION:${milestone.description} - Generated by ${appName}`,
      'STATUS:CONFIRMED',
      'TRANSP:TRANSPARENT', // Show as "Available" so it doesn't block the whole day, typically preferred for reminders
      'END:VEVENT',
    ].join(lineBreak) + lineBreak;

    icsContent += event;
  });

  icsContent += 'END:VCALENDAR';
  return icsContent;
};

export const downloadICS = (filename: string, content: string) => {
  const element = document.createElement('a');
  const file = new Blob([content], {type: 'text/calendar'});
  element.href = URL.createObjectURL(file);
  element.download = filename;
  document.body.appendChild(element); // Required for this to work in FireFox
  element.click();
  document.body.removeChild(element);
};
